version: "3.9"

services:
  client:
    build: ./
    env_file:
      - ./.env
    environment:
      OPENAI_API_KEY: ${OPENAI_KEY}
      SERVER_PORT: 8081
      SPRING_AI_MCP_CLIENT_SSE_CONNECTIONS_SERVER1_URL: ${SERVER_IP}
    ports:
      - "8081:8081"
volumes:
  mysql_data:
networks:
  default:
    external: true
    name: shared-net
